In [9]:
import numpy as np

A = np.array([[0, 1],
              [2, 3],
              [4, 5]])

B = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7]])

print("行列A:")
print(A)
print("\n行列B:")
print(B)

result = np.dot(A, B)

print("\n行列の積 A × B:")
print(result)

max_value = np.max(result)
print(f"\n計算結果の最大値: {max_value}")

行列A:
[[0 1]
 [2 3]
 [4 5]]

行列B:
[[0 1 2 3]
 [4 5 6 7]]

行列の積 A × B:
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]

計算結果の最大値: 47
